#include<stdio.h>
#include<stdlib.h>
#include<math.h>
int main()
{
	printf("Hello World\n");
	system("color ae");
	system("color bd");
	system("color cc");
	system("color db");
	system("color ea");
	system("color 0f");
	system("mode con:cols=90 lines=20");
	system("Loading Powershell Advanced Version...");
	system("cls&echo Loading...&ping -n 2 127.0.0.1 >nul");
	system("cls&echo Windows PowerShell");
	system("powershell -NoLogo for($i = 1; $i -lt 101; $i++ ) {write-progress -activity Updating -status Loading-Powershell... -percentcomplete $i}");
	system("color 0e");
	system("ping -n 2 127.0.0.1 >nul");
	system("cls&echo Windows PowerShell Advanced 高级版");
	system("powershell -NoLogo for($i = 1; $i -lt 10; $i++ ) {write-progress -activity Updating -status Injecting-Advanced-Command... -percentcomplete $i}");
	system("ping -n 2 127.0.0.1 >nul");
	printf("版权所有 (C) 2020 JSG Corporation。保留所有权利。");
	printf("\n");
	printf("\n");
	printf("使用Get-Help来获取帮助");
	printf("\n");
	printf("使用Get-command来获取命令");
	printf("\n");
	printf("使用exit来退出");
	printf("\n");
	printf("\n");
	system("powershell -NoLogo for($i = 1; $i -lt 30; $i++ ) {write-progress -activity Updating -status Cleaning... -percentcomplete $i}");
	system("powershell -NoLogo ");
	printf("\n");
	printf("\n");
	system("pause");
}